version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
